name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: Build and Analyze
    runs-on: ubuntu-latest
    defaults:
      run:
        # Esto asegura que todos los comandos 'run' se ejecuten desde expedienteService/
        working-directory: expedienteService 

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # --- MANTÉN TUS PASOS DE DEPURACIÓN para verificar la ruta ---
      - name: Debug - Print Current Directory
        run: pwd 

      - name: Debug - List Directory Contents
        run: ls -la
      # --- FIN DE PASOS DE DEPURACIÓN ---

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      # --- ¡NUEVO PASO CRÍTICO: Instalar la librería local! ---
      - name: Install local SgData_SgLib_WSEthCipher JAR
        run: |
          mvn install:install-file \
          -Dfile=lib/SgData_SgLib_WSEthCipher-1.0-1.jar \
          -DgroupId=com.seguridata.wseth \
          -DartifactId=SgData_SgLib_WSEthCipher \
          -Dversion=1.0-1 \
          -Dpackaging=jar \
          -DgeneratePom=true
        # Nota: El path 'lib/SgData_SgLib_WSEthCipher-1.0-1.jar' es relativo a working-directory: expedienteService
      # --------------------------------------------------------

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Roaau_expediente
