name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: Build and Analyze
    runs-on: ubuntu-latest
    # ESTO YA ESTÁ FUNCIONANDO CORRECTAMENTE
    defaults:
      run:
        working-directory: expedienteService 

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Pasos de depuración: MUY IMPORTANTES para confirmar el directorio actual
      # Aquí, 'pwd' debería imprimir '/home/runner/work/expediente/expediente/expedienteService'
      - name: Debug - Print Current Directory (after checkout)
        run: pwd 

      - name: Debug - List Directory Contents (after checkout)
        run: ls -la

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      # Este paso instala el JAR. Sigue siendo necesario.
      - name: Install local SgData_SgLib_WSEthCipher JAR
        run: |
          mvn install:install-file \
          -Dfile=lib/SgData_SgLib_WSEthCipher-1.0-1.jar \
          -DgroupId=com.seguridata.wseth \
          -DartifactId=SgData_SgLib_WSEthCipher \
          -Dversion=1.0-1 \
          -Dpackaging=jar \
          -DgeneratePom=true

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Construye y analiza el proyecto con SonarQube
      - name: Build and analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          # ¡ELIMINA LA SIGUIENTE LÍNEA!
          # cd expedienteService 
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Roaau_expediente
