name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: Build and Analyze
    runs-on: ubuntu-latest
    # Este 'defaults' debería hacer que todos los comandos 'run' se ejecuten desde 'expedienteService/'
    # Pero hemos añadido un 'cd' explícito en el paso 'Build and analyze with SonarQube' por seguridad.
    defaults:
      run:
        working-directory: expedienteService 

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Pasos de depuración: imprimen el directorio actual y su contenido. Útiles para verificar.
      - name: Debug - Print Current Directory (after checkout)
        run: pwd 

      - name: Debug - List Directory Contents (after checkout)
        run: ls -la

      # Configura el JDK 17 necesario para tu proyecto Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      # Paso para instalar la librería 'SgData_SgLib_WSEthCipher' en el repositorio Maven local del runner.
      # Asegúrate de que el JAR esté en 'expedienteService/lib/' en tu repositorio.
      - name: Install local SgData_SgLib_WSEthCipher JAR
        run: |
          mvn install:install-file \
          -Dfile=lib/SgData_SgLib_WSEthCipher-1.0-1.jar \
          -DgroupId=com.seguridata.wseth \
          -DartifactId=SgData_SgLib_WSEthCipher \
          -Dversion=1.0-1 \
          -Dpackaging=jar \
          -DgeneratePom=true
        # Nota: El path 'lib/SgData_SgLib_WSEthCipher-1.0-1.jar' es relativo al 'working-directory' configurado arriba.

      # Caché de paquetes de SonarQube para acelerar builds futuros
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Caché de paquetes de Maven para acelerar builds futuros
      - name: Cache Maven packages
        uses: actions/cache@v4 # Corregido de 'actions:cache@v4' a 'actions/cache@v4'
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Construye y analiza el proyecto con SonarQube
      - name: Build and analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          # Nos aseguramos de estar en el directorio correcto antes de ejecutar Maven
          cd expedienteService 
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Roaau_expediente
